---
- name: Build CA on Control Node
  hosts: managenode
  become: true

  tasks:
    - name: Install Python OpenSSL package
      apt:
        name:
          - openssl

    - name: Generate CA private key
      openssl_privatekey:
        path: /etc/pki/tls/private/ca.key
        state: present

    - name: Generate CA certificate
      openssl_certificate:
        path: /etc/pki/tls/certs/ca.crt
        privatekey_path: /etc/pki/tls/private/ca.key
        csr_path: /etc/pki/tls/private/ca.csr
        state: present
        validity_days: 3650
        serial: 1
        country: US
        state: Virginia
        organization: ExampleOrg
        unit: ExampleUnit
        common_name: ExampleCA
        email: rootca@enova-conseil.com

    - name: Copy CA certificate to target hosts
      copy:
        src: /etc/pki/tls/certs/ca.crt
        dest: /etc/pki/ca-trust/source/anchors/ca.crt
      delegate_to: "{{ item }}"
      with_items: "{{ groups['kafka'] }}"

    - name: Update CA Trust
      command: "update-ca-trust extract"
